localStorage.clear();
const employees = [
  {
    id: 1,
    name: "Amit Sharma",
    email: "employee1@example.com",
    password: "123",
    profession: "Software Engineer",
    role: "Developer",
    tasks: [
      {
        title: "Develop Authentication Module",
        description: "Implement JWT-based authentication system.",
        date: "2025-02-08",
        category: "Development",
        assignTo: "employee1@example.com",
        active: true,
        newTask: true,
        completedTask: false,
        failedTask: false,
      },
      {
        title: "Fix UI Bugs",
        description: "Resolve alignment issues in the navbar.",
        date: "2025-02-06",
        category: "UI Fix",
        assignTo: "employee1@example.com",
        active: false,
        newTask: false,
        completedTask: true,
        failedTask: false,
      },
    ],
    taskCount: {
      active: 1,
      newTask: 1,
      completedTask: 1,
      failedTask: 0,
    },
  },
  {
    id: 2,
    name: "Rajesh Verma",
    email: "employee2@example.com",
    password: "123",
    profession: "Data Scientist",
    role: "Analyst",
    tasks: [
      {
        title: "Data Cleaning Script",
        description: "Write a script to clean raw dataset for analysis.",
        date: "2025-02-07",
        category: "Data Processing",
        assignTo: "employee2@example.com",
        active: true,
        newTask: false,
        completedTask: false,
        failedTask: false,
      },
      {
        title: "Train ML Model",
        description: "Train a classification model using TensorFlow.",
        date: "2025-02-05",
        category: "Machine Learning",
        assignTo: "employee2@example.com",
        active: false,
        newTask: false,
        completedTask: false,
        failedTask: true,
      },
    ],
    taskCount: {
      active: 1,
      newTask: 0,
      completedTask: 0,
      failedTask: 1,
    },
  },
  {
    id: 3,
    name: "Suresh Yadav",
    email: "employee3@example.com",
    password: "123",
    profession: "Project Manager",
    role: "Manager",
    tasks: [
      {
        title: "Sprint Planning",
        description: "Organize the next sprint backlog with the team.",
        date: "2025-02-08",
        category: "Management",
        assignTo: "employee3@example.com",
        active: true,
        newTask: true,
        completedTask: false,
        failedTask: false,
      },
      {
        title: "Client Meeting",
        description: "Present project updates to stakeholders.",
        date: "2025-02-04",
        category: "Meetings",
        assignTo: "employee3@example.com",
        active: false,
        newTask: false,
        completedTask: true,
        failedTask: false,
      },
    ],
    taskCount: {
      active: 1,
      newTask: 1,
      completedTask: 1,
      failedTask: 0,
    },
  },
  {
    id: 4,
    name: "Priya Mehta",
    email: "employee4@example.com",
    password: "123",
    profession: "UI/UX Designer",
    role: "Designer",
    tasks: [
      {
        title: "Design Dashboard Layout",
        description: "Create wireframes for the admin dashboard.",
        date: "2025-02-06",
        category: "UI/UX Design",
        assignTo: "employee4@example.com",
        active: false,
        newTask: false,
        completedTask: true,
        failedTask: false,
      },
      {
        title: "Improve Mobile Responsiveness",
        description: "Optimize UI for mobile devices.",
        date: "2025-02-08",
        category: "UI/UX",
        assignTo: "employee4@example.com",
        active: true,
        newTask: true,
        completedTask: false,
        failedTask: false,
      },
    ],
    taskCount: {
      active: 1,
      newTask: 1,
      completedTask: 1,
      failedTask: 0,
    },
  },
  {
    id: 5,
    name: "Vikram Singh",
    email: "employee5@example.com",
    password: "123",
    profession: "DevOps Engineer",
    role: "Engineer",
    tasks: [
      {
        title: "Set Up CI/CD Pipeline",
        description: "Configure Jenkins for automated deployment.",
        date: "2025-02-07",
        category: "DevOps",
        assignTo: "employee5@example.com",
        active: true,
        newTask: false,
        completedTask: false,
        failedTask: false,
      },
      {
        title: "Optimize Server Performance",
        description: "Analyze logs and optimize server configurations.",
        date: "2025-02-06",
        category: "Infrastructure",
        assignTo: "employee5@example.com",
        active: false,
        newTask: false,
        completedTask: true,
        failedTask: false,
      },
    ],
    taskCount: {
      active: 1,
      newTask: 0,
      completedTask: 1,
      failedTask: 0,
    },
  },
];

const admin = [
  {
    id: 1,
    name: "Anil Kumar",
    email: "admin@example.com",
    password: "123",
    profession: "System Administrator",
    role: "Admin",
    tasks: [
      {
        title: "User Access Audit",
        description: "Review system access logs for security compliance.",
        date: "2025-02-08",
        category: "Security",
        assignTo: "admin@example.com",
        active: true,
        newTask: true,
        completedTask: false,
        failedTask: false,
      },
      {
        title: "Update Server Patches",
        description: "Apply latest security patches to all production servers.",
        date: "2025-02-06",
        category: "Infrastructure",
        assignTo: "admin@example.com",
        active: false,
        newTask: false,
        completedTask: true,
        failedTask: false,
      },
    ],
    taskCount: {
      active: 1,
      newTask: 1,
      completedTask: 1,
      failedTask: 0,
    },
  },
];

export const setLocalStorage = () => {
  localStorage.setItem("employees", JSON.stringify(employees));
  localStorage.setItem("admin", JSON.stringify(admin));
};

export const getLocalStorage = () => {
  const employees = JSON.parse(localStorage.getItem("employees"));
  const admin = JSON.parse(localStorage.getItem("admin"));
  return { employees, admin };
};
